### ISSUE TITLE
GCP logging errors - Log entry with size 369.7K exceeds maximum size of 256.0K

### ISSUE THREAD

**Issue by KyleJu** [GoogleChrome/chromium-dashboard#2250]
There have been recurring [logging errors](https://pantheon.corp.google.com/errors/detail/CMqw_tm0kdiacw;time=P7D?project=cr-status) seen in GCP - InvalidArgument: 400 Log entry with size 369.7K exceeds maximum size of 256.0K.

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/logging_v2/handlers/transports/background_thread.py", line 114, in _safely_commit_batch
    batch.commit()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/logging_v2/logger.py", line 453, in commit
    client.logging_api.write_entries(entries, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/logging_v2/_gapic.py", line 160, in write_entries
    self._gapic_api.write_log_entries(request=request)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/logging_v2/services/logging_service_v2/client.py", line 631, in write_log_entries
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Log entry with size 369.7K exceeds maximum size of 256.0K 
```

**Comment by KyleJu** [comment]
Related to https://github.com/googleapis/python-logging/issues/53

**Comment by ayyoubelamrani4** [comment]
This is solved with https://github.com/googleapis/python-logging/issues/53 right?

**Comment by siddhiguptas** [comment]
Hey @KyleJu !! I am interested in assisting with this issue.. Is this issue still open?

**Comment by meshach567** [comment]
Hi @KyleJu !! Pls, I am asking if this issue is still open

**Comment by pradyut4u** [comment]
hi i would like to work on this issue if its available

**Comment by KAkhinish2108** [comment]
Hi, @KyleJu , This is Akhinish, I'd like to work on this issue. Let me know if this approach and solution is acceptable.

The recurring GCP logging error is caused by log entries exceeding the 256 KB size limit, likely due to large payloads (e.g., full file contents, stack traces, or model responses) being logged.

Approach:

i .Identify log statements producing oversized entries.
ii. Determine which fields (payloads, responses, traces) are contributing most to log size.
iii. Define a safe logging strategy that preserves signal without dumping large data.

Solution:

i. Truncate or summarize large log fields before logging.
ii. Avoid logging full file contents or model outputs; log metadata instead (file path, size, counts, hashes).
iii. Add size checks before emitting logs and skip or compress entries that exceed limits.
iv. Optionally log large data to storage (GCS) and reference it via a link or ID in logs.

This will eliminate GCP logging failures while keeping logs useful and production-safe.
